name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Install dependencies
        run: pnpm i
      - run: pnpm test:main


  preload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Install dependencies
        run: pnpm i
      - run: pnpm test:preload


  renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Install dependencies
        run: pnpm i
      - run: pnpm test:renderer


  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Install dependencies
        run: pnpm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npx playwright install --with-deps chromium
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm test:e2e
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm test:e2e
        if: matrix.os != 'ubuntu-latest'
