name: Typechecking
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.svelte'
      - '**/tsconfig.json'
      - 'package-lock.json'
      - '.github/workflows/typechecking.yml'
  pull_request:
    paths:
      - '**.ts'
      - '**.svelte'
      - '**/tsconfig.json'
      - 'package-lock.json'
      - '.github/workflows/typechecking.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16 # Need for pnpm >=7.4
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm ci

      - run: pnpm run typecheck
